[server]
maxUploadSize = 500
runOnSave = true
headless = true

[theme]
base="light"
primaryColor="#0ea5e9"
backgroundColor="#f8fafc"
secondaryBackgroundColor="#f1f5f9"
textColor="#0f172a"
font="sans serif"
